[toolchain]
anchor_version = "0.31.1"
solana_version = "1.18.26"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.mainnet]
wwars = "9A2bft4ehF3zGTid1o6TC828Ww2mmNhmqGC3PzHd4EXw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
types = "../apps/web/src/idl"
